server:
  port: 8888

spring:
  application:
    name: k8s-kube-eventer

k8s:
  cluster:
    config:
      url: your_url
      token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi10b2tlbi1sN3hiOCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImQ1MDRiOTkyLTgxZDQtMTFlOS05MWIwLWFlYjJlNWUyZmYwYyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTphZG1pbiJ9.YfZwOnwquxXJKX7az08Y8nFSUso0AxYr-weOV9Q8l3HRM-

event:
  config:
    kind: Pod,Node
  sink:
    webhook:
      url: http://127.0.0.1:8080/v1/event/webhook

    elasticsearch:
      serverUrl: your_url
      serverPort: 9200
      username: elastic
      password: your_password


